# DEFAULT environment

# database configuration
spring:
  datasource:
    url: jdbc:h2:file:~/urlshortener-dev-h2database
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework: debug

# urlshortener configuration
url-shortener:
  baseurl: http://localhost:8080/
  token:
    length: 3
    characters: abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789
    max-attempts: 5
